export const casesData = [
  // --- EXISTING REFINED CASES ---
  {
    id: '1402',
    title: 'The Dizzy Grandma',
    description: 'Elderly patient with polypharmacy presenting with dizziness.',
    difficulty: 1200,
    category: 'Geriatrics',
    specialty: 'Cardio',
    scenarioType: 'Diagnosis',
    targetAudience: 'General',
    pattern: 'Hypotension',
    medicines: JSON.stringify(['Lisinopril', 'HCTZ', 'Metformin']),
    patientData: JSON.stringify({
      name: "Mrs. Edith Miller",
      dob: "12/04/1951",
      age: 73,
      allergy: "PCN",
      vitals: { hr: 112, bp: "88/52", temp: 37.2 },
      history: {
        hpi: "Patient presents to ED via ambulance c/o extreme dizziness and generalized weakness starting 2 hours ago. Found by daughter on bathroom floor.",
        pmh: ["Hypertension (HTN)", "Type 2 Diabetes (T2DM)", "Chronic Kidney Disease (Stage 3)"],
        meds: ["Lisinopril 40mg daily", "Metformin 1000mg BID", "Amlodipine 10mg daily", "HCTZ 25mg daily (Refill picked up yesterday)"],
      },
      progress: { current: 1, total: 3 },
    }),
    scenario: JSON.stringify({
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=House&eyebrows=angry&mouth=serious",
      doctorName: "Attending Physician (Dr. Grumpy)",
      prompt: "Look at those vitals. She's hypotensive (88/52), tachycardic, and dry as a bone. She just refilled her diuretic (HCTZ) yesterday. How would you treat her, or are you trying to lower the population today?",
    }),
    quiz: JSON.stringify({
      options: [
        {
          id: "option1",
          label: "Option A",
          text: "Administer Lisinopril 40mg PO to control rate.",
          isCorrect: false,
          feedback: "Lisinopril is an ACE inhibitor which lowers blood pressure. Giving this to a patient with a BP of 88/52 will likely cause vascular collapse."
        },
        {
          id: "option2",
          label: "Option B",
          text: "Hold antihypertensives, start IV fluids (Normal Saline).",
          isCorrect: true,
        },
        {
          id: "option3",
          label: "Option C",
          text: "Start Metoprolol 5mg IV push.",
          isCorrect: false,
          feedback: "Beta-blockers like Metoprolol reduce heart rate and contractility. While she is tachycardic, it is a compensatory response to hypotension. Blocking it could cause shock."
        },
        {
          id: "option4",
          label: "Option D",
          text: "Discharge home with instructions to drink water.",
          isCorrect: false,
          feedback: "She is hemodynamically unstable. Discharging her is malpractice."
        },
      ],
      feedback: {
        success: {
          title: "Saved her.",
          message: "Insurance hates you because staying in the hospital is expensive, but good job. She was dehydrated and over-medicated. Holding the ACE/Diuretic and giving fluids fixed the perfusion.",
        },
        fail: {
          title: "Congrats, she's dead.",
          message: "You just gave a hypotensive patient more antihypertensives or failed to resuscitate. You bottomed out her pressure and caused organ failure.",
        },
      },
    }),
  },
  {
    id: '1403',
    title: 'Tylenol Trouble',
    description: 'Teenager with intentional overdose.',
    difficulty: 1400,
    category: 'Toxicology',
    specialty: 'ID',
    scenarioType: 'Management',
    targetAudience: 'Professional',
    pattern: 'Hepatotoxicity',
    medicines: JSON.stringify(['Acetaminophen', 'NAC']),
    patientData: JSON.stringify({
      name: "Tyler Noll",
      dob: "05/12/2008",
      age: 16,
      allergy: "NKDA",
      vitals: { hr: 90, bp: "118/72", temp: 36.8 },
      history: {
        hpi: "16yo male brought in by parents after admitting to ingesting 'a handful' of pills 4 hours ago. Bottle found was Extra Strength Tylenol.",
        pmh: ["Depression", "Asthma"],
        meds: ["Albuterol PRN", "Sertraline 50mg daily"],
      },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cuddy",
      doctorName: "Dr. Cuddy",
      prompt: "4 hour level came back at 180 mcg/mL. The Rumack-Matthew nomogram indicates significant hepatotoxicity risk. We need to start the antidote immediately. What is it?",
    }),
    quiz: JSON.stringify({
      options: [
        {
          id: "opt1",
          label: "Option A",
          text: "Naloxone (Narcan)",
          isCorrect: false,
          feedback: "Naloxone is the antidote for Opioids, not Acetaminophen."
        },
        {
          id: "opt2",
          label: "Option B",
          text: "N-acetylcysteine (NAC)",
          isCorrect: true,
        },
        {
          id: "opt3",
          label: "Option C",
          text: "Flumazenil",
          isCorrect: false,
          feedback: "Flumazenil is the antidote for Benzodiazepines. It can also precipitate seizures."
        },
        {
          id: "opt4",
          label: "Option D",
          text: "Activated Charcoal",
          isCorrect: false,
          feedback: "Activated Charcoal is most effective within 1 hour of ingestion. At 4 hours, it is less likely to be effective, and NAC is the priority."
        },
      ],
      feedback: {
        success: {
          title: "Correct.",
          message: "NAC replenishes glutathione stores and prevents hepatic necrosis. Good catch on the timing.",
        },
        fail: {
          title: "Liver Failure Imminent.",
          message: "That is not the antidote. The patient's liver is now failing while you guess random drugs.",
        },
      },
    }),
  },
  // ... (More existing cases would go here, refined similarly) ...
  
  // --- NEW LAYPERSON CASES ---
  {
    id: "case-lay-new-1",
    title: "The Coffee Spill",
    description: "Hot coffee spilled on a hand.",
    difficulty: 800,
    category: "Trauma",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Burn",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Joe",
      dob: "1990-01-01",
      age: 34,
      allergy: "None",
      vitals: { hr: 100, bp: "120/80", temp: 37.0 },
      history: { hpi: "Spilled boiling coffee on right hand. Skin is red and blistering.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Burn Nurse",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nurse",
      prompt: "Ouch! That looks like a second-degree burn. What is the best way to cool it down immediately?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Put butter on it", isCorrect: false, feedback: "Butter traps heat and increases the risk of infection. Never put grease on a burn." },
        { id: "b", label: "B", text: "Run cool (not cold) water over it for 20 minutes", isCorrect: true },
        { id: "c", label: "C", text: "Pack it in ice", isCorrect: false, feedback: "Ice can cause further tissue damage (frostbite on top of a burn) and constrict blood flow." },
      ],
      feedback: {
        success: { title: "Correct", message: "Cool running water dissipates heat and stops the burning process." },
        fail: { title: "Ouch", message: "That would make it worse. Cool water is the only way." },
      },
    }),
  },
  {
    id: "case-lay-new-2",
    title: "Nosebleed Nightmare",
    description: "It just won't stop.",
    difficulty: 800,
    category: "ENT",
    specialty: "ENT",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Epistaxis",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Tim",
      dob: "2015-05-05",
      age: 9,
      allergy: "None",
      vitals: { hr: 100, bp: "110/70", temp: 37.0 },
      history: { hpi: "Nose started bleeding while playing. It's been 10 minutes.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "School Nurse",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=SchoolNurse",
      prompt: "He's bleeding all over his shirt. How should he position his head?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Tilt head back", isCorrect: false, feedback: "Tilting back causes blood to run down the throat, which can cause vomiting or choking." },
        { id: "b", label: "B", text: "Tilt head forward and pinch the soft part of the nose", isCorrect: true },
        { id: "c", label: "C", text: "Lie down flat", isCorrect: false, feedback: "Lying down increases blood pressure to the head and can worsen bleeding." },
      ],
      feedback: {
        success: { title: "Correct", message: "Leaning forward prevents swallowing blood. Pinching applies pressure to the bleeding vessel." },
        fail: { title: "Messy", message: "Now he's swallowing blood. Lean forward!" },
      },
    }),
  },
  // --- MORE LAYPERSON CASES ---
  {
    id: "case-lay-new-6",
    title: "Eye Chemical Splash",
    description: "Cleaning product in the eye.",
    difficulty: 850,
    category: "Ophthalmology",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Chemical Burn",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Cleaner Carl",
      dob: "1995-01-01",
      age: 29,
      allergy: "None",
      vitals: { hr: 110, bp: "130/80", temp: 37.0 },
      history: { hpi: "Splashed bleach in right eye. Pain is 10/10.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Dispatcher",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dispatch2",
      prompt: "Bleach in the eye! He's screaming. What should he do RIGHT NOW?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Keep the eye closed and drive to ER", isCorrect: false, feedback: "Closing the eye traps the chemical against the cornea, causing more damage." },
        { id: "b", label: "B", text: "Flush with water for at least 15 minutes", isCorrect: true },
        { id: "c", label: "C", text: "Put eye drops (Visine) in", isCorrect: false, feedback: "Visine won't wash out the chemical. You need volume." },
      ],
      feedback: {
        success: { title: "Correct", message: "Dilution is the solution to pollution. Flush, flush, flush." },
        fail: { title: "Blindness Risk", message: "You must wash the chemical out immediately." },
      },
    }),
  },
  {
    id: "case-lay-new-7",
    title: "The Limping Child",
    description: "Toddler refuses to walk.",
    difficulty: 900,
    category: "Pediatrics",
    specialty: "Ortho",
    scenarioType: "Triage",
    targetAudience: "Layperson",
    pattern: "Trauma",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Toddler",
      dob: "2022-01-01",
      age: 2,
      allergy: "None",
      vitals: { hr: 100, bp: "90/50", temp: 37.0 },
      history: { hpi: "Went down slide with dad. Now crying and won't put weight on left leg.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Pediatrician",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Peds3",
      prompt: "Classic 'slide injury'. The tibia likely twisted. What is this fracture called?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Toddler's Fracture", isCorrect: true },
        { id: "b", label: "B", text: "Compound Fracture", isCorrect: false, feedback: "Compound means the bone is sticking out through the skin." },
        { id: "c", label: "C", text: "Growing Pains", isCorrect: false, feedback: "Growing pains are bilateral and at night, not acute after injury." },
      ],
      feedback: {
        success: { title: "Correct", message: "A spiral fracture of the tibia, common when a foot gets stuck while sliding." },
        fail: { title: "Incorrect", message: "This is a specific injury mechanism." },
      },
    }),
  },
  {
    id: "case-lay-new-8",
    title: "Faint at the Sight of Blood",
    description: "Vasovagal syncope.",
    difficulty: 800,
    category: "Cardiology",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Syncope",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Squeamish Steve",
      dob: "2000-01-01",
      age: 24,
      allergy: "None",
      vitals: { hr: 50, bp: "90/60", temp: 37.0 },
      history: { hpi: "Saw a needle, turned pale, and passed out. Woke up 10 seconds later.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Nurse",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nurse2",
      prompt: "He's waking up but feels woozy. Should we stand him up?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Yes, walk it off", isCorrect: false, feedback: "Standing up too soon can cause him to faint again." },
        { id: "b", label: "B", text: "No, keep him lying down with legs raised", isCorrect: true },
        { id: "c", label: "C", text: "Give him CPR", isCorrect: false, feedback: "He has a pulse and is breathing. CPR is for cardiac arrest." },
      ],
      feedback: {
        success: { title: "Correct", message: "Legs up helps blood return to the brain." },
        fail: { title: "Incorrect", message: "Keep him down to prevent a second fall." },
      },
    }),
  },
  {
    id: "case-lay-new-9",
    title: "Dog Bite",
    description: "Neighbor's dog got aggressive.",
    difficulty: 850,
    category: "Infectious Disease",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Trauma",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Mailman",
      dob: "1980-01-01",
      age: 44,
      allergy: "None",
      vitals: { hr: 90, bp: "130/80", temp: 37.0 },
      history: { hpi: "Bitten on calf. Puncture wounds. Bleeding controlled.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Urgent Care",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=UC",
      prompt: "We cleaned it. Do we stitch it up tight?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Yes, close it tightly", isCorrect: false, feedback: "Dog bites are dirty. Closing them traps bacteria and causes infection." },
        { id: "b", label: "B", text: "No, leave it open (or loose sutures) to drain", isCorrect: true },
        { id: "c", label: "C", text: "Put superglue on it", isCorrect: false, feedback: "Never glue a dirty bite wound." },
      ],
      feedback: {
        success: { title: "Correct", message: "Dog bites are high risk for infection. We usually leave them open to heal by secondary intention." },
        fail: { title: "Infection Risk", message: "You just trapped Pasteurella bacteria inside his leg." },
      },
    }),
  },
  {
    id: "case-lay-new-10",
    title: "Super Glue Mistake",
    description: "Glued fingers together.",
    difficulty: 800,
    category: "Dermatology",
    specialty: "ER",
    scenarioType: "Home Remedy",
    targetAudience: "Layperson",
    pattern: "Chemical",
    medicines: JSON.stringify(["Acetone"]),
    patientData: JSON.stringify({
      name: "Crafter",
      dob: "1990-01-01",
      age: 34,
      allergy: "None",
      vitals: { hr: 80, bp: "120/80", temp: 37.0 },
      history: { hpi: "Spilled super glue. Thumb and index finger are stuck together.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Friend",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Friend2",
      prompt: "They are really stuck. Pulling hurts. What household item dissolves super glue?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Water", isCorrect: false, feedback: "Water actually cures (hardens) super glue faster." },
        { id: "b", label: "B", text: "Nail Polish Remover (Acetone)", isCorrect: true },
        { id: "c", label: "C", text: "Butter", isCorrect: false, feedback: "Butter might help slide, but won't dissolve the bond." },
      ],
      feedback: {
        success: { title: "Correct", message: "Acetone dissolves cyanoacrylate (super glue)." },
        fail: { title: "Stuck", message: "That won't work. Try Acetone." },
      },
    }),
  },

  // --- MORE PROFESSIONAL CASES ---
  {
    id: "case-pro-new-11",
    title: "Ectopic Pregnancy",
    description: "Abdominal pain in early pregnancy.",
    difficulty: 1500,
    category: "OBGYN",
    specialty: "OBGYN",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Acute Abdomen",
    medicines: JSON.stringify(["Methotrexate"]),
    patientData: JSON.stringify({
      name: "Sarah",
      dob: "1995-01-01",
      age: 29,
      allergy: "None",
      vitals: { hr: 110, bp: "100/60", temp: 37.0 },
      history: { hpi: "RLQ pain, vaginal spotting. LMP 6 weeks ago. Positive home pregnancy test.", pmh: ["PID"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "OBGYN",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=OB",
      prompt: "Beta-hCG is 1500. Ultrasound shows empty uterus. What is the diagnosis until proven otherwise?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Appendicitis", isCorrect: false, feedback: "Possible, but positive pregnancy test makes Ectopic the priority." },
        { id: "b", label: "B", text: "Ectopic Pregnancy", isCorrect: true },
        { id: "c", label: "C", text: "Normal Pregnancy", isCorrect: false, feedback: "With hCG of 1500, we should see a sac in the uterus. Empty uterus = Ectopic." },
        { id: "d", label: "D", text: "Ovarian Cyst", isCorrect: false, feedback: "Must rule out Ectopic first." },
      ],
      feedback: {
        success: { title: "Correct", message: "This is a medical emergency. Rupture can cause fatal hemorrhage." },
        fail: { title: "Incorrect", message: "You cannot miss an ectopic. It kills young women." },
      },
    }),
  },
  {
    id: "case-pro-new-12",
    title: "Cauda Equina Syndrome",
    description: "Back pain with red flags.",
    difficulty: 1550,
    category: "Neurology",
    specialty: "Ortho",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Spine",
    medicines: JSON.stringify(["Steroids"]),
    patientData: JSON.stringify({
      name: "Mr. Back",
      dob: "1970-01-01",
      age: 54,
      allergy: "None",
      vitals: { hr: 90, bp: "140/90", temp: 37.0 },
      history: { hpi: "Severe lower back pain after lifting. Now has numbness in the 'saddle area' and urinary retention.", pmh: ["Herniated Disc"], meds: ["Ibuprofen"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Spine Surgeon",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Spine",
      prompt: "Saddle anesthesia and retention. This is Cauda Equina. What is the treatment?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Physical Therapy", isCorrect: false, feedback: "This is a surgical emergency." },
        { id: "b", label: "B", text: "Epidural Steroid Injection", isCorrect: false, feedback: "Too slow. The nerves are being crushed." },
        { id: "c", label: "C", text: "Emergency Decompression Surgery", isCorrect: true },
        { id: "d", label: "D", text: "Muscle Relaxers", isCorrect: false, feedback: "He needs surgery now to save bladder function." },
      ],
      feedback: {
        success: { title: "Correct", message: "Time is spine. Decompression must happen within 24-48 hours." },
        fail: { title: "Paralyzed", message: "He is now permanently incontinent because you delayed surgery." },
      },
    }),
  },
  {
    id: "case-pro-new-13",
    title: "Tension Pneumothorax",
    description: "Trauma with hypotension.",
    difficulty: 1500,
    category: "Trauma",
    specialty: "ER",
    scenarioType: "Procedure",
    targetAudience: "Professional",
    pattern: "Shock",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Trauma Tim",
      dob: "1990-01-01",
      age: 34,
      allergy: "None",
      vitals: { hr: 140, bp: "70/40", temp: 37.0, spo2: 85 },
      history: { hpi: "Stabbed in right chest. Trachea deviated to LEFT. Absent breath sounds on RIGHT.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Trauma Surgeon",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Trauma",
      prompt: "He's crashing. Tracheal deviation confirms Tension Pneumo. Do NOT wait for X-ray. What do you do?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Intubate", isCorrect: false, feedback: "Positive pressure ventilation will increase the tension and kill him faster." },
        { id: "b", label: "B", text: "Needle Decompression (Thoracostomy)", isCorrect: true },
        { id: "c", label: "C", text: "Chest X-ray", isCorrect: false, feedback: "He will be dead before the X-ray is taken." },
        { id: "d", label: "D", text: "Start IV Fluids", isCorrect: false, feedback: "Fluids won't fix the obstructive shock." },
      ],
      feedback: {
        success: { title: "Correct", message: "Immediate needle decompression converts the tension pneumo to a simple pneumo." },
        fail: { title: "Dead", message: "You waited too long or intubated, causing cardiovascular collapse." },
      },
    }),
  },
  {
    id: "case-pro-new-14",
    title: "Digoxin Toxicity",
    description: "Yellow halos and nausea.",
    difficulty: 1550,
    category: "Cardiology",
    specialty: "Cardio",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Toxicity",
    medicines: JSON.stringify(["Digibind"]),
    patientData: JSON.stringify({
      name: "Grandma Dig",
      dob: "1940-01-01",
      age: 84,
      allergy: "None",
      vitals: { hr: 40, bp: "100/60", temp: 37.0 },
      history: { hpi: "Nausea, vomiting, confusion. Says lights have 'yellow halos'.", pmh: ["AFib", "Heart Failure"], meds: ["Digoxin", "Furosemide"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Cardiologist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cardio3",
      prompt: "Classic Dig toxicity. Potassium is 5.5. What is the specific antidote?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Atropine", isCorrect: false, feedback: "Might help HR temporarily, but doesn't fix the toxicity." },
        { id: "b", label: "B", text: "Digoxin Immune Fab (Digibind)", isCorrect: true },
        { id: "c", label: "C", text: "Dialysis", isCorrect: false, feedback: "Digoxin has a large volume of distribution and is not dialyzable." },
        { id: "d", label: "D", text: "Calcium Gluconate", isCorrect: false, feedback: "Controversial, but historically thought to cause 'stone heart' in Dig toxicity." },
      ],
      feedback: {
        success: { title: "Correct", message: "Digibind binds the free drug." },
        fail: { title: "Incorrect", message: "She needs the specific antibody fragments." },
      },
    }),
  },
  {
    id: "case-pro-new-15",
    title: "Serotonin Syndrome",
    description: "Agitated, hyperreflexic, clonus.",
    difficulty: 1500,
    category: "Psychiatry",
    specialty: "Psych",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Toxicity",
    medicines: JSON.stringify(["Cyproheptadine"]),
    patientData: JSON.stringify({
      name: "Raver",
      dob: "2000-01-01",
      age: 24,
      allergy: "None",
      vitals: { hr: 130, bp: "160/90", temp: 39.0 },
      history: { hpi: "Took 'Ecstasy' while on SSRIs. Now agitated, sweating, tremors, and hyperreflexia (clonus).", pmh: ["Depression"], meds: ["Zoloft"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Psychiatrist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Psych",
      prompt: "Serotonin Syndrome. Benzos help, but what is the specific serotonin antagonist?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Dantrolene", isCorrect: false, feedback: "That's for Malignant Hyperthermia (rigid, not hyperreflexic)." },
        { id: "b", label: "B", text: "Cyproheptadine", isCorrect: true },
        { id: "c", label: "C", text: "Bromocriptine", isCorrect: false, feedback: "That's for NMS (Neuroleptic Malignant Syndrome)." },
        { id: "d", label: "D", text: "Haloperidol", isCorrect: false, feedback: "Avoid antipsychotics, they can worsen hyperthermia." },
      ],
      feedback: {
        success: { title: "Correct", message: "Cyproheptadine is a 5-HT2 receptor antagonist." },
        fail: { title: "Incorrect", message: "Look for the specific antagonist." },
      },
    }),
  },
  // --- FINAL BATCH LAYPERSON ---
  {
    id: "case-lay-new-11",
    title: "The Silent Choker",
    description: "Baby swallowed a coin.",
    difficulty: 900,
    category: "Pediatrics",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Airway",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Baby Bob",
      dob: "2023-01-01",
      age: 1,
      allergy: "None",
      vitals: { hr: 140, bp: "90/50", temp: 37.0 },
      history: { hpi: "Playing with coins. Suddenly silent, drooling, not coughing.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Mom",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mom",
      prompt: "He's not making any noise! He's turning blue! Do I stick my finger in his throat?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Yes, do a blind finger sweep", isCorrect: false, feedback: "Blind sweeps can push the object further down. Only sweep if you SEE the object." },
        { id: "b", label: "B", text: "Back blows and chest thrusts", isCorrect: true },
        { id: "c", label: "C", text: "Heimlich Maneuver", isCorrect: false, feedback: "For infants < 1 year, we do back blows/chest thrusts, not abdominal thrusts (Heimlich)." },
      ],
      feedback: {
        success: { title: "Correct", message: "5 back blows, 5 chest thrusts. Keep head lower than chest." },
        fail: { title: "Incorrect", message: "You risked pushing it deeper." },
      },
    }),
  },
  {
    id: "case-lay-new-12",
    title: "Seizure in the Pool",
    description: "Swimming lesson emergency.",
    difficulty: 950,
    category: "Neurology",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Drowning",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Swimmer",
      dob: "2010-01-01",
      age: 14,
      allergy: "None",
      vitals: { hr: 0, bp: "0/0", temp: 36.0 },
      history: { hpi: "Had a seizure in the water. Submerged for 2 minutes. Pulled out, not breathing.", pmh: ["Epilepsy"], meds: ["Keppra"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Lifeguard",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lifeguard2",
      prompt: "He's not breathing and has no pulse. I'm starting CPR. Should I try to get the water out of his lungs first?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Yes, push on his stomach", isCorrect: false, feedback: "This causes vomiting and aspiration. Do not delay CPR." },
        { id: "b", label: "B", text: "No, start Chest Compressions immediately", isCorrect: true },
        { id: "c", label: "C", text: "Give rescue breaths only", isCorrect: false, feedback: "He has no pulse. He needs compressions." },
      ],
      feedback: {
        success: { title: "Correct", message: "There is usually not much water in the lungs (laryngospasm). Compressions are priority." },
        fail: { title: "Incorrect", message: "Delaying compressions kills brain cells." },
      },
    }),
  },
  {
    id: "case-lay-new-13",
    title: "Electric Shock",
    description: "DIY project gone wrong.",
    difficulty: 850,
    category: "Trauma",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Electrocution",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Sparky",
      dob: "1990-01-01",
      age: 34,
      allergy: "None",
      vitals: { hr: 120, bp: "140/90", temp: 37.0 },
      history: { hpi: "Touched a live wire. Thrown back. Hand is burned.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Electrician",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sparky",
      prompt: "He's still holding the wire! He's shaking! What do I do?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Grab him and pull him off", isCorrect: false, feedback: "You will get shocked too and become a second victim." },
        { id: "b", label: "B", text: "Turn off the main breaker / Unplug the cord", isCorrect: true },
        { id: "c", label: "C", text: "Throw water on him", isCorrect: false, feedback: "Water conducts electricity. Are you trying to kill everyone?" },
      ],
      feedback: {
        success: { title: "Correct", message: "Cut the power source first. If not possible, use a non-conductive object (wood) to push him away." },
        fail: { title: "Shocking", message: "Now you are both being electrocuted." },
      },
    }),
  },
  {
    id: "case-lay-new-14",
    title: "Asthma Attack without Inhaler",
    description: "Camping trip emergency.",
    difficulty: 850,
    category: "Pulmonology",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Respiratory",
    medicines: JSON.stringify(["Caffeine"]),
    patientData: JSON.stringify({
      name: "Wheezy",
      dob: "2000-01-01",
      age: 24,
      allergy: "None",
      vitals: { hr: 110, bp: "120/80", temp: 37.0 },
      history: { hpi: "Forgot inhaler. Having an asthma attack. Wheezing.", pmh: ["Asthma"], meds: ["Albuterol"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Camper",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Camper",
      prompt: "We are miles from help. No inhaler. What common drink might help a little?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Strong Coffee (Caffeine)", isCorrect: true },
        { id: "b", label: "B", text: "Alcohol", isCorrect: false, feedback: "Depresses respiration. Bad idea." },
        { id: "c", label: "C", text: "Milk", isCorrect: false, feedback: "Increases mucus thickness." },
      ],
      feedback: {
        success: { title: "Correct", message: "Caffeine is chemically similar to Theophylline, a bronchodilator. It's a weak substitute but better than nothing." },
        fail: { title: "Incorrect", message: "Caffeine is the only thing that might help open airways." },
      },
    }),
  },
  {
    id: "case-lay-new-15",
    title: "Frostbite Fingers",
    description: "Skiing without gloves.",
    difficulty: 800,
    category: "Environmental",
    specialty: "ER",
    scenarioType: "First Aid",
    targetAudience: "Layperson",
    pattern: "Cold Injury",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Skier",
      dob: "1995-01-01",
      age: 29,
      allergy: "None",
      vitals: { hr: 80, bp: "120/80", temp: 36.0 },
      history: { hpi: "Fingers are white, hard, and numb after losing gloves.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Ski Patrol",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ski",
      prompt: "They are frozen. Should we rub them to warm them up?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Yes, rub vigorously with snow", isCorrect: false, feedback: "Rubbing causes tissue damage to the ice crystals in the cells. Never rub frostbite." },
        { id: "b", label: "B", text: "Use warm (not hot) water to rewarm", isCorrect: true },
        { id: "c", label: "C", text: "Hold them over a fire", isCorrect: false, feedback: "Numb skin burns easily. Dry heat is dangerous." },
      ],
      feedback: {
        success: { title: "Correct", message: "Rapid rewarming in warm water (37-39C) is the treatment." },
        fail: { title: "Incorrect", message: "Rubbing destroys tissue. Use warm water." },
      },
    }),
  },

  // --- FINAL BATCH PROFESSIONAL ---
  {
    id: "case-pro-new-16",
    title: "Hypertensive Emergency",
    description: "BP 220/120 with vision changes.",
    difficulty: 1500,
    category: "Cardiology",
    specialty: "Cardio",
    scenarioType: "Management",
    targetAudience: "Professional",
    pattern: "HTN",
    medicines: JSON.stringify(["Nicardipine", "Labetalol"]),
    patientData: JSON.stringify({
      name: "Mr. Pressure",
      dob: "1960-01-01",
      age: 64,
      allergy: "None",
      vitals: { hr: 90, bp: "220/120", temp: 37.0 },
      history: { hpi: "Blurry vision, headache. Papilledema on exam.", pmh: ["HTN"], meds: ["Non-compliant"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "ER Doc",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ER2",
      prompt: "End organ damage present. We need to lower BP. How fast?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Normalize to 120/80 immediately", isCorrect: false, feedback: "Dropping BP too fast causes cerebral ischemia (stroke)." },
        { id: "b", label: "B", text: "Lower by max 25% in first hour", isCorrect: true },
        { id: "c", label: "C", text: "Give oral meds and wait", isCorrect: false, feedback: "This is an emergency. IV meds are needed." },
      ],
      feedback: {
        success: { title: "Correct", message: "Controlled reduction prevents watershed strokes." },
        fail: { title: "Stroke", message: "You dropped the pressure too fast and caused a stroke." },
      },
    }),
  },
  {
    id: "case-pro-new-17",
    title: "Status Asthmaticus - Intubation",
    description: "Impending respiratory arrest.",
    difficulty: 1600,
    category: "Critical Care",
    specialty: "Pulm",
    scenarioType: "Procedure",
    targetAudience: "Professional",
    pattern: "Airway",
    medicines: JSON.stringify(["Ketamine"]),
    patientData: JSON.stringify({
      name: "Asthma Amy",
      dob: "2000-01-01",
      age: 24,
      allergy: "None",
      vitals: { hr: 150, bp: "100/60", temp: 37.0, spo2: 80 },
      history: { hpi: "Silent chest, lethargic, pH 7.1, pCO2 80. Needs intubation.", pmh: ["Asthma"], meds: ["Albuterol"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Intensivist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ICU",
      prompt: "We have to tube her. Which induction agent is a bronchodilator?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Etomidate", isCorrect: false, feedback: "Hemodynamically stable but no bronchodilation." },
        { id: "b", label: "B", text: "Ketamine", isCorrect: true },
        { id: "c", label: "C", text: "Propofol", isCorrect: false, feedback: "Can cause hypotension." },
      ],
      feedback: {
        success: { title: "Correct", message: "Ketamine releases catecholamines and relaxes bronchial smooth muscle." },
        fail: { title: "Incorrect", message: "Ketamine is the agent of choice for severe asthma." },
      },
    }),
  },
  {
    id: "case-pro-new-18",
    title: "Hyperkalemia",
    description: "Peaked T waves.",
    difficulty: 1450,
    category: "Nephrology",
    specialty: "Nephro",
    scenarioType: "Management",
    targetAudience: "Professional",
    pattern: "Electrolyte",
    medicines: JSON.stringify(["Calcium", "Insulin"]),
    patientData: JSON.stringify({
      name: "Renal Ron",
      dob: "1950-01-01",
      age: 74,
      allergy: "None",
      vitals: { hr: 60, bp: "130/80", temp: 37.0 },
      history: { hpi: "Missed dialysis. Potassium 7.2. ECG shows peaked T waves.", pmh: ["ESRD"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Nephrologist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nephro",
      prompt: "ECG changes are present. What is the FIRST drug to give?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Insulin + Dextrose", isCorrect: false, feedback: "This shifts K+, but doesn't protect the heart. It's step 2." },
        { id: "b", label: "B", text: "Calcium Gluconate", isCorrect: true },
        { id: "c", label: "C", text: "Kayexalate", isCorrect: false, feedback: "Takes hours to work." },
        { id: "d", label: "D", text: "Albuterol", isCorrect: false, feedback: "Adjunctive only." },
      ],
      feedback: {
        success: { title: "Correct", message: "Calcium stabilizes the cardiac membrane to prevent arrhythmias." },
        fail: { title: "Cardiac Arrest", message: "You must stabilize the membrane first with Calcium." },
      },
    }),
  },
  {
    id: "case-pro-new-19",
    title: "Aortic Dissection",
    description: "Tearing chest pain.",
    difficulty: 1550,
    category: "Cardiology",
    specialty: "Cardio",
    scenarioType: "Management",
    targetAudience: "Professional",
    pattern: "Vascular",
    medicines: JSON.stringify(["Esmolol"]),
    patientData: JSON.stringify({
      name: "Mr. Tear",
      dob: "1960-01-01",
      age: 64,
      allergy: "None",
      vitals: { hr: 110, bp: "190/110", temp: 37.0 },
      history: { hpi: "Sudden tearing chest pain radiating to back. Unequal pulses.", pmh: ["HTN"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Vascular Surgeon",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vasc",
      prompt: "Type B Dissection. We need to lower BP and Heart Rate (shear stress). Which goes first?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Vasodilator (Nitroprusside)", isCorrect: false, feedback: "Vasodilation causes reflex tachycardia, increasing shear stress and ripping the aorta further." },
        { id: "b", label: "B", text: "Beta Blocker (Esmolol)", isCorrect: true },
        { id: "c", label: "C", text: "Hydralazine", isCorrect: false, feedback: "Causes reflex tachycardia." },
      ],
      feedback: {
        success: { title: "Correct", message: "Beta blockers reduce dP/dt (shear stress). Vasodilators can be added AFTER rate is controlled." },
        fail: { title: "Rupture", message: "Reflex tachycardia tore the aorta. Patient deceased." },
      },
    }),
  },
  {
    id: "case-pro-new-20",
    title: "Addisonian Crisis",
    description: "Hypotension and hyperpigmentation.",
    difficulty: 1500,
    category: "Endocrine",
    specialty: "Endo",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Shock",
    medicines: JSON.stringify(["Hydrocortisone"]),
    patientData: JSON.stringify({
      name: "Addie",
      dob: "1980-01-01",
      age: 44,
      allergy: "None",
      vitals: { hr: 110, bp: "80/50", temp: 37.0 },
      history: { hpi: "Weakness, vomiting, weight loss. Hyperpigmented skin. Na 130, K 5.5.", pmh: ["Autoimmune"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Endocrinologist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Endo3",
      prompt: "Adrenal crisis. Fluids aren't working. What is the missing hormone?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Thyroxine", isCorrect: false },
        { id: "b", label: "B", text: "Hydrocortisone (Steroids)", isCorrect: true },
        { id: "c", label: "C", text: "Insulin", isCorrect: false },
        { id: "d", label: "D", text: "Vasopressin", isCorrect: false },
      ],
      feedback: {
        success: { title: "Correct", message: "She needs glucocorticoids and mineralocorticoids immediately." },
        fail: { title: "Incorrect", message: "This is adrenal insufficiency. She needs steroids." },
      },
    }),
  },
  {
    id: "case-pro-new-21",
    title: "Carbon Monoxide Poisoning",
    description: "Headache in winter.",
    difficulty: 1400,
    category: "Toxicology",
    specialty: "ER",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Toxicity",
    medicines: JSON.stringify(["Oxygen"]),
    patientData: JSON.stringify({
      name: "Family",
      dob: "1990-01-01",
      age: 34,
      allergy: "None",
      vitals: { hr: 100, bp: "120/80", temp: 37.0, spo2: 100 },
      history: { hpi: "Whole family has headaches and nausea. Using a generator indoors.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "ER Doc",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ER3",
      prompt: "Pulse Ox reads 100%. Why is that misleading?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "It's broken", isCorrect: false },
        { id: "b", label: "B", text: "Pulse Ox cannot distinguish Oxyhemoglobin from Carboxyhemoglobin", isCorrect: true },
        { id: "c", label: "C", text: "They are not hypoxic", isCorrect: false },
      ],
      feedback: {
        success: { title: "Correct", message: "CO binds hemoglobin 200x stronger than O2. You need a Co-Oximeter." },
        fail: { title: "Incorrect", message: "Standard pulse ox sees bright red blood and thinks it's oxygen." },
      },
    }),
  },
  {
    id: "case-pro-new-22",
    title: "Meningitis",
    description: "Fever, stiff neck, rash.",
    difficulty: 1500,
    category: "Infectious Disease",
    specialty: "ID",
    scenarioType: "Management",
    targetAudience: "Professional",
    pattern: "Infection",
    medicines: JSON.stringify(["Ceftriaxone", "Vancomycin"]),
    patientData: JSON.stringify({
      name: "Student",
      dob: "2004-01-01",
      age: 20,
      allergy: "None",
      vitals: { hr: 120, bp: "100/60", temp: 39.5 },
      history: { hpi: "College student. Headache, photophobia, stiff neck. Petechial rash.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "ID Specialist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ID",
      prompt: "Suspected Meningococcal Meningitis. LP will take an hour. What do you do?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Wait for LP results", isCorrect: false, feedback: "Delay kills. Treat empirically." },
        { id: "b", label: "B", text: "Start Antibiotics immediately (after blood cultures)", isCorrect: true },
        { id: "c", label: "C", text: "CT Head first", isCorrect: false, feedback: "CT is good, but don't delay antibiotics for it." },
      ],
      feedback: {
        success: { title: "Correct", message: "Never delay antibiotics for LP or CT in suspected bacterial meningitis." },
        fail: { title: "Dead", message: "He died while waiting for the LP." },
      },
    }),
  },
  {
    id: "case-pro-new-23",
    title: "Testicular Torsion",
    description: "Sudden groin pain.",
    difficulty: 1450,
    category: "Urology",
    specialty: "Uro",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Ischemia",
    medicines: JSON.stringify([]),
    patientData: JSON.stringify({
      name: "Teen",
      dob: "2008-01-01",
      age: 16,
      allergy: "None",
      vitals: { hr: 110, bp: "130/80", temp: 37.0 },
      history: { hpi: "Sudden severe left scrotal pain. Nausea. High riding testicle.", pmh: ["None"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Urologist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Uro",
      prompt: "Absent cremasteric reflex. Time is testicle. What is the window for salvage?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "24 hours", isCorrect: false },
        { id: "b", label: "B", text: "6 hours", isCorrect: true },
        { id: "c", label: "C", text: "12 hours", isCorrect: false },
      ],
      feedback: {
        success: { title: "Correct", message: "After 6 hours, ischemia leads to necrosis." },
        fail: { title: "Too Late", message: "You lost the testicle." },
      },
    }),
  },
  {
    id: "case-pro-new-24",
    title: "Orbital Cellulitis",
    description: "Swollen eye, painful movement.",
    difficulty: 1500,
    category: "Ophthalmology",
    specialty: "Ophtho",
    scenarioType: "Diagnosis",
    targetAudience: "Professional",
    pattern: "Infection",
    medicines: JSON.stringify(["Antibiotics"]),
    patientData: JSON.stringify({
      name: "Kid",
      dob: "2015-01-01",
      age: 9,
      allergy: "None",
      vitals: { hr: 100, bp: "110/70", temp: 38.5 },
      history: { hpi: "Swollen red eye. Pain with eye movement (Ophthalmoplegia). Proptosis.", pmh: ["Sinusitis"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "Ophthalmologist",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eye",
      prompt: "Preseptal vs Orbital. Pain with movement and proptosis confirms Orbital. What is the major complication we fear?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Conjunctivitis", isCorrect: false },
        { id: "b", label: "B", text: "Cavernous Sinus Thrombosis / Brain Abscess", isCorrect: true },
        { id: "c", label: "C", text: "Cataracts", isCorrect: false },
      ],
      feedback: {
        success: { title: "Correct", message: "Infection can spread posteriorly to the brain." },
        fail: { title: "Incorrect", message: "This is a life-threatening intracranial extension risk." },
      },
    }),
  },
  {
    id: "case-pro-new-25",
    title: "Ludwig's Angina",
    description: "Toothache leading to swollen neck.",
    difficulty: 1550,
    category: "ENT",
    specialty: "ENT",
    scenarioType: "Airway",
    targetAudience: "Professional",
    pattern: "Infection",
    medicines: JSON.stringify(["Antibiotics"]),
    patientData: JSON.stringify({
      name: "Mr. Tooth",
      dob: "1980-01-01",
      age: 44,
      allergy: "None",
      vitals: { hr: 110, bp: "130/80", temp: 39.0 },
      history: { hpi: "Bad molar. Now neck is woody, hard, and swollen. Tongue elevated ('Bull Neck').", pmh: ["Dental Caries"], meds: ["None"] },
      progress: { current: 1, total: 1 },
    }),
    scenario: JSON.stringify({
      doctorName: "ENT Surgeon",
      doctorImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ENT",
      prompt: "This is a submandibular space infection. What is the immediate threat?",
    }),
    quiz: JSON.stringify({
      options: [
        { id: "a", label: "A", text: "Sepsis", isCorrect: false },
        { id: "b", label: "B", text: "Airway Obstruction", isCorrect: true },
        { id: "c", label: "C", text: "Tooth loss", isCorrect: false },
      ],
      feedback: {
        success: { title: "Correct", message: "The tongue is pushed up and back, occluding the airway. Secure airway immediately." },
        fail: { title: "Dead", message: "He suffocated." },
      },
    }),
  }
];
