export const MOTIVATIONAL_PHRASES = [
  "This knowledge could save a life one day.",
  "You are now better prepared for a real emergency.",
  "In a crisis, your quick thinking would make all the difference.",
  "You just learned how to be a hero in real life.",
  "This isn't just a game; it's training for the real world.",
  "Your preparation is a gift to your loved ones.",
  "One day, knowing this answer might matter more than anything.",
  "You are becoming the person people can rely on.",
  "Every case you solve makes the world a little safer.",
  "You're building the confidence to act when it counts.",
  "Imagine the difference you could make with this knowledge.",
  "You are better prepared than 90% of the population.",
  "Your instincts are sharpening. Keep going.",
  "You're not just playing; you're learning to save lives.",
  "The world needs more people prepared like you.",
  "You've got the potential to be a real-life hero.",
  "This is the kind of knowledge that changes outcomes.",
  "You are taking responsibility for the safety of others.",
  "Great job! You're ready to handle this if it happens.",
  "Your dedication to learning this is admirable.",
  "Think of the lives you could impact with this skill.",
  "You are arming yourself with life-saving wisdom.",
  "This is how you prepare to make a difference.",
  "You're one step closer to being a lifesaver.",
  "Your future self will thank you for learning this.",
  "You are proving that you can handle pressure.",
  "This is what preparedness looks like.",
  "You're doing the work that most people skip.",
  "You are a valuable asset in any emergency.",
  "Keep it up! You are mastering life-saving skills.",
  "You just proved you have what it takes.",
  "This knowledge is power—the power to save.",
  "You are making yourself indispensable.",
  "You're learning to protect the people around you.",
  "That was a critical decision, and you nailed it.",
  "You are building a toolkit for saving lives.",
  "This is more than a high score; it's real impact.",
  "You are developing a protector's mindset.",
  "You're getting ready for the moments that matter.",
  "This is how everyday heroes are made.",
  "You are bridging the gap between bystander and lifesaver.",
  "Your awareness could be the difference between life and death.",
  "You are empowering yourself to help others.",
  "This is a victory for preparedness.",
  "You are showing true leadership potential.",
  "You're learning to stay calm and effective.",
  "This is the most important game you'll ever play.",
  "You are investing in the safety of your community.",
  "You're proving that you care enough to be ready.",
  "Keep going. The world needs you ready."
];
